### ISSUE TITLE
OpenTimestamps inclusion as a sources instead of library

### ISSUE THREAD

**Issue by RCasatta** [guardianproject/proofmode#39]
Hi, OpenTimestamps dev here, I was just wondering why OpenTimestamps is included as sources and not as maven/gradle [library](https://search.maven.org/#artifactdetails%7Ccom.eternitywall%7Cjava-opentimestamps%7C1.14%7Cjar)

**Comment by n8fr8** [comment]
Hi, and thanks for checking in! I noticed in these projects https://github.com/eternitywall/android-opentimestamps and https://github.com/lvaccaro/AndroidOpenTimestamps that the library had been forked and included as source, and just followed that approach. I was also concerned with potential dependencies and was hoping to ensure all the XML and JSON code was using Android specific packages.

Of course, I have no desire to fork or have to deal with maintaining and updating this code separately, so any thoughts and guidance on a better approach is welcome!

**Comment by RCasatta** [comment]
Got it, I would like to develop the library such that including sources is not needed in the future. I will keep you posted.
@lvaccaro could give you more details about why he needed to include sources on the android-opentimestamps app

**Comment by n8fr8** [comment]
I would love to hear more, and definitely would prefer just to reference a maintained library!

**Comment by RCasatta** [comment]
In this moment we are focusing on the javascript lib, when we finish we will dedicate some time to update the java lib, I'll let you know

**Comment by RCasatta** [comment]
I would like to tell you app https://github.com/eternitywall/android-opentimestamps is now referencing the maven lib version 1.15
Hope it can be useful for your app too, and let us know if you have any problem

**Comment by n8fr8** [comment]
done!
