### ISSUE TITLE
Share link to pgp.mit.edu not working

### ISSUE THREAD

**Issue by WU6V5L48** [guardianproject/proofmode#61]
![CopyQ nS7181](https://user-images.githubusercontent.com/27091594/59067901-c98a8280-8880-11e9-9249-a4a6b731d888.png)

Maybe this is MIT's problem, just thought I'd report

Thanks

**Comment by guland2000** [comment]
It is always like this. It does not matter)

**Comment by n8fr8** [comment]
Yes, it is an issue with that server. We are thinking how we handle key publishing / sharing.

**Comment by n8fr8** [comment]
Share public key in the ProofMode menu now sends as an attachment to any email or messenger app
