### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [guardianproject/proofmode#68]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by n8fr8** [comment]
Done!

New release for testing:
https://github.com/guardianproject/proofmode/releases/tag/0.0.14-BETA-1

**Comment by Neustradamus** [comment]
@n8fr8: Good job, thanks!

**Comment by Neustradamus** [comment]
@n8fr8: Note that there is a 1.69 since more one month, can you update it before the final build?

**Comment by n8fr8** [comment]
done
https://github.com/guardianproject/proofmode/releases/tag/0.0.14-BETA-2
