### ISSUE TITLE
Fdroid app missing (404 not found)

### ISSUE THREAD

**Issue by emanuelb** [guardianproject/proofmode#73]
Visiting:
https://guardianproject.info/apps/org.witness.proofmode/
The "GET IT ON F-DROID" image point to package name `org.witness.proofmode`:
https://f-droid.org/packages/org.witness.proofmode
which return 404, using fdroid search for "ProofMode" or "proofmode" return nothing.

**Comment by n8fr8** [comment]
It is a part of the Guardian Project repo which you need to enable separately: https://guardianproject.info/fdroid/

We also have a new website https://proofmode.org
