### ISSUE TITLE
Signal and Zip Files

### ISSUE THREAD

**Issue by YurkoWasHere** [guardianproject/proofmode#81]
It seems from skimming old issues and the code base that proofmode should be able to send zip files to signal users.

However we cant seem to get this to work.

Phone: Galaxy S10FE

Process:
- Take a picture
- Share with ProofMode
- Generate Proof
- Share Robust
- Signal
- Notes To Self (or any use really)

What gets shared is the image only. 
Additionally Basic Share only shares text about the image, but no image itself.

Almost seems like its supposed to share multiple files (like it does for email) but it only shares one file when sending to signal.
(basic share does not include image either when sending to email)

**Comment by n8fr8** [comment]
Thanks for the report. Will reproduce and figure it out. Signal does have issues accepting multiple files for some reason.

**Comment by YurkoWasHere** [comment]
Do you have any sense in timeline when this can be looked at?

We are working on putting together a pipeline for a project and hoping proofmode can be included in this pipeline. But without the zip component it will not work for us.

Do you know if there was a version that did work? Perhaps we can roll back to a previous version.

Thanks again for all your work on this!

**Comment by n8fr8** [comment]
Next week!

**Comment by YurkoWasHere** [comment]
Wondering how its coming along?

We managed to compile the code without any attestations (commented it out because of API keys required) and it seemed to work as expected (with zips)

Don't know if that gives you a place to look.

**Comment by YurkoWasHere** [comment]
I have noticed that with my "patch" version, the first (ie after a reboot of the phone) "Share Robust" would just share the JPG as if it was a simple share. However subsequent "Share Robust" would be the zip file as expected.

(Playstore version not working at all for zips)

**Comment by YurkoWasHere** [comment]
Another observation - if you share directly to a signal number it wont zip, but sharing to Signal then selecting the number in signal will.

**Comment by benhylau** [comment]
These are the steps I followed (back in Dec) but was unable to get a .zip file for sharing to Signal.

1. Install ProofMode.

    ![signal-2021-12-19-021205_002](https://user-images.githubusercontent.com/2261308/146667125-09a7440b-4684-4521-983d-6bfe7c8cbd5a.png)

1. Configure ProofMode and ensure location access is allowed all the time.

    ![signal-2021-12-19-021205_003](https://user-images.githubusercontent.com/2261308/146667126-6fee9d2d-398e-4b34-9d9d-c5b90f3d6320.png)

1. Take a photo and share to ProofMode.

    ![signal-2021-12-19-021205_004](https://user-images.githubusercontent.com/2261308/146667127-f1419b95-3e02-4216-bfe9-a7694bd38d45.png)

1. Select `SHARE ROBUST`.

    ![signal-2021-12-19-021205_005](https://user-images.githubusercontent.com/2261308/146667129-e373c341-540a-40a6-9151-1a86fee6e72a.png)

1. Share to Signal. Observe that the files are not in a self-contained zip.

    ![signal-2021-12-19-021205_001](https://user-images.githubusercontent.com/2261308/146667124-30b43586-7898-45ea-acdc-edadc17c2ed6.png)

**Comment by n8fr8** [comment]
We've now changed to all sharing to be done as a single zip file for all apps. This makes the process cleaner, simpler and more reliable.

Please test!

New release tagged and APK posted: https://github.com/guardianproject/proofmode/releases/tag/0.0.14-RC-2

**Comment by YurkoWasHere** [comment]
Initial tests show the zip function to work.  

Note that image is missing when doing basic share in signal (only text)

![image](https://user-images.githubusercontent.com/39072689/152580834-8d9cb2f1-6862-4dff-90a3-dbd773c74fe4.png)

**Comment by n8fr8** [comment]
There isn't mean to be an image there. It is just proof only, to say a file exists, I have it, here is the claim that it exists.
