### ISSUE TITLE
columns missing in proof data if data isn't captured

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/proofmode#82]
Lat/Lon columns are missing if they are not captured, which can be confusing to some tools and parsing scripts. Instead, they should be included with empty or -1 values.

**Comment by kweenkeen** [comment]
Yeah, I've written my code so that it can properly capture NaN values, so empty columns would be ideal.

**Comment by n8fr8** [comment]
Lat Lon columns should always be there now. If the Location.provider reads "none" you should ignore the values though. They will still be "0".
