### ISSUE TITLE
OnePlus 9 Pro / Android 12 removes loc data using Share-function

### ISSUE THREAD

**Issue by brylcreem** [guardianproject/proofmode#83]
So, this took some trouble shooting to figure out.

I recently upgraded to Android 12 on Oneplus 9 Pro, and Proofmode works every time on that. Great!

But location data weren't coming over when sharing robust proof.

It turns out that the Share function from the Gallery removes the location data from the image file. When I tried to transfer an image using a USB cable, it worked fine.

I have removed the point about the hash verification breaking.

The hash is taken of the file after the location data is removed, so the hash value in the _proof.cvs_ fits the file.

The CVS-file:
![hashValueCVS](https://user-images.githubusercontent.com/646021/151176795-c5c7dd73-1622-4ce0-9d3d-e1993d0f8779.png)

Share function
008D82FC728102138FCEC76220085FEA81ADC3E6AA432CA966EA805509D7199A
USB
2D2D2CBB8B8D3DCC69D63C6257409B2324E8D7CE807C07D45F3C9893F0CC5FB7

![hashcheckFailed](https://user-images.githubusercontent.com/646021/151148764-c534beec-1904-4287-9a08-f3169497d3a7.png)

Also, I tried attaching the image in Gmail, and the location data survived that, so it's apparently only the Gallery share that's affected?

Not a Proofmode issue, but maybe something to keep in mind.

Share function
![OP9_noGPS](https://user-images.githubusercontent.com/646021/151146274-1de2851c-56cf-45b4-84c7-450fa3c9d28d.png)

USB cable
![OP9_GPS](https://user-images.githubusercontent.com/646021/151146337-451bd4e6-e1d3-4b11-a812-2b1f0aa3d943.png)

**Comment by n8fr8** [comment]
Robust now shares everything inside of a zipfile to keep all media intact. Please let us know if this solves the problem for you.

**Comment by brylcreem** [comment]
It doesn't - the image file in the zip still has the GPS data zeroed out.

![gpsZero](https://user-images.githubusercontent.com/646021/152872823-820196f5-af0f-444a-9d25-ae9d5199ed18.jpg)

The SHA256 hash is taken after the GPS data is zeroed out.
![HashCheck](https://user-images.githubusercontent.com/646021/152872863-39833585-119d-4717-8005-dc736a17cb26.jpg)
![sha256](https://user-images.githubusercontent.com/646021/152873053-2bf8659c-f980-4016-a268-6c16c7bcad98.png)

**Comment by n8fr8** [comment]
We generate the sha256 hash 30 seconds after we are notified the new media file exists. If the geo coords are in the EXIF at that point, then the hash we use in ProofMode should match that file. 

Just to point out, there is signed/verified location data in the proof.csv itself. Also, are you sure there isn't a setting somewhere where could turn this zeroing out of the geo coordinates off? Maybe in the Gallery app?

**Comment by brylcreem** [comment]
Something weird is going on, and I don't think it's the gallery. The subject line of this issue might have to be changed.

I tested on my old Oneplus 7 Pro with Android 11, and it has the same problem, so it doesn't seem to be Android 12 either.

When I share a picture (1) from the gallery using OneDrive, the GPS data is intact. 

When I share from the gallery using Proofmode (2), the image file in the zip has GPS-data zeroed out, BEFORE the hash value is calculated.

The two hash values from (1) and (2) are different.

![hashCheckFailed02](https://user-images.githubusercontent.com/646021/153058819-45148a66-bd1c-467a-8c36-ed6e9a209396.png)

As you can see from the file names in the explorer window, the zip-file was generated in Proofmode at 19:55 (12-hour time), and the picture was taken at 19:47, so I waited for around 8 minutes before sharing the proof.

The hash value in the zip file names matches the hash of the image file with the GPS-data zeroed out.

![gpsZero02](https://user-images.githubusercontent.com/646021/153060757-e5737cd1-d005-42b4-a509-b5b0ffe0ba64.jpg)

Exif-data from the two files. Note that it's differently organized from the Oneplus 9 Pro camera.

But I find it odd that no one else is reporting this issue. Is it only Oneplus phones? Or do I make bad juju towards Proofmode?

**Comment by brylcreem** [comment]
I just tested again on a Samsung S8+ running Android 9 and the image file shared directly from the Gallery and the image file in the zip file have the same hash, and they both have GPS-data in Exif and the proof file.

So the problem doesn't show up there.

It must be some weird Oneplus, or "me" bug 😬
