### ISSUE TITLE
SHA256 in robust mode does not match

### ISSUE THREAD

**Issue by YurkoWasHere** [guardianproject/proofmode#85]
Reported hash of photo: `4245e4a723cf4645bd9dd2a0c08299bad0ab7efed740e76af9487da978f8de85`

Using basic share (file hashed on end point)
```
CertUtil -hashfile 20211117_212208.jpg SHA256
SHA256 hash of 20211117_212208.jpg:
4245e4a723cf4645bd9dd2a0c08299bad0ab7efed740e76af9487da978f8de85
```

Using robust share (file hashed on end point)
```
CertUtil -hashfile 20211117_212208(1).jpg SHA256
SHA256 hash of 20211117_212208(1).jpg:
7f05d26f464dbbc0d3a324d4bf139536baa152c14952eb593e9eeaa7eecbcbb8
```

Did a hex dump to see the difference in the two files
```
< 00000310  00 00 00 00 00 06 00 03  00 02 00 00 00 02 00 00  |................|
< 00000360  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
< 00000370  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
< 00000380  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
< 00000390  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
< 000003a0  00 00 00 00 00 00 00 09  01 00 00 04 00 00 00 01  |................|
```
--vs--
```
> 00000310  00 00 00 00 00 06 00 03  00 02 00 00 00 02 45 00  |..............E.|
> 00000360  00 00 00 00 00 00 00 00  00 01 00 00 00 00 00 00  |................|
> 00000370  00 01 00 00 00 00 00 00  27 10 00 00 00 00 00 00  |........'.......|
> 00000380  03 e8 00 00 00 00 00 00  00 01 00 00 00 00 00 00  |................|
> 00000390  00 01 00 00 00 00 00 00  00 01 31 39 37 30 3a 30  |..........1970:0|
> 000003a0  31 3a 30 31 00 00 00 09  01 00 00 04 00 00 00 01  |1:01............|
```

Looking at this via an properties in windows the latter has "gps coordinates" embedded. (They are 0,0 but that COULD be not having a gps lock?) But the SHA256 hash matches the file that does not have these modifications.

![image](https://user-images.githubusercontent.com/39072689/152416632-bf6ce5d9-bb99-47a8-a3c6-03db6de660fe.png)

Cant identify where the 1970:01:01 (epoc) is.

If i had to guess, I'd guess that the problem is that the SHA256 is generated before additional meta data is (attempted to be ?) added to the file.

**Comment by n8fr8** [comment]
New release tagged and APK posted: https://github.com/guardianproject/proofmode/releases/tag/0.0.14-RC-2

Includes a small time delay before proof is generated for a file, in hopes that any geo exif insertion or other EXIF modifications would be completed by the time the sha256 hash is generated.

More testing will need to be done to verify this en masse.

**Comment by YurkoWasHere** [comment]
Tested RC2

Reported hash: b87b8183438abd0af0488aafac9e11077a50fe8f30ee284f35eb2e6a1915b1ad

```
CertUtil -hashfile 20220204_130323.jpg SHA256
SHA256 hash of 20220204_130323.jpg:
b87b8183438abd0af0488aafac9e11077a50fe8f30ee284f35eb2e6a1915b1ad
CertUtil: -hashfile command completed successfully.
```

Hash now matches ✅
