### ISSUE TITLE
Can't "Open Photo" after using "Share Public Key"

### ISSUE THREAD

**Issue by johnhess** [guardianproject/proofmode#96]
To replicate:

1. Open the app
2. From the top right menu, select "Share Public Key..."
3. Dismiss the pop up modality selector (or share, it doesn't matter)
4. From the top right menu, select "Open Photo"

*Expected Result:* The camera roll is opened for selection
*Actual Result:* The pop up modality selector is opened again

Workaround: Quitting the app and reopening, one can access the camera roll using the top right menu.

version 1.0 (6)

**Comment by n8fr8** [comment]
This seems like an iOS issue?

**Comment by johnhess** [comment]
🤦 yep.  will open it there instead.

**Comment by n8fr8** [comment]
https://gitlab.com/guardianproject/proofmode/proofmode-ios
